---
- name: create monitoring directory
  file:
    path: "{{ bbb_monitoring_all_in_one_directory }}"
    state: directory



- name: copy docker files into place
  template:
    src: "monitoring/{{ item }}.j2"
    dest: "{{ bbb_monitoring_all_in_one_directory }}/{{ item }}"
  with_items:
    - bbb_exporter_secrets.env
    - docker-compose.yaml
    - prometheus.yaml
  notify: restart monitoring

- name: copy monitoring nginx configuration file
  template:
    src: "monitoring/monitoring.nginx.j2"
    dest: "/etc/bigbluebutton/nginx/monitoring.nginx"
  notify: reload nginx

- name: start monitoring
  docker_compose:
    pull: true
    project_src: /root/bbb-monitoring/
  when: bbb_monitoring_all_in_one_enable | bool
