---
- name: Install ufw
  apt:
    pkg: ufw
    state: present

- name: Configure ufw rules
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - src: "ufw/user.rules.j2"
      dest: "/etc/ufw/user.rules"
    - src: "ufw/user6.rules.j2"
      dest: "/etc/ufw/user6.rules"

- name: Activate ufw
  community.general.ufw:
    state: enabled
    policy: "{{ bbb_firewall_ufw['policy'] | default('deny', true) }}"
