---
- name: add BigBlueButton apt key
  apt_key:
    url: "{{ bbb_apt_mirror }}/repo/bigbluebutton.asc"
    id: '{{ bbb_apt_key }}'
    state: present

- name: add mongodb apt key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ bbb_mongodb_version | default('4.2') }}.asc"
    state: present

- name: add multiverse apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"
    - "deb http://repo.mongodb.org/apt/ubuntu/ {{ ansible_distribution_release | lower }}/mongodb-org/{{ bbb_mongodb_version }} multiverse"
    - "deb https://ubuntu.bigbluebutton.org/bionic-230/ bigbluebutton-bionic main"

- name: add Bionic dependency apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:bigbluebutton/support
    - ppa:rmescandon/yq
    - ppa:certbot/certbot
